name: Build and deploy PHP app to local server - w-crops

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install zip utility
        run: sudo apt-get install zip -y

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build --if-present

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Zip artifact for deployment
        run: sudo zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: self-hosted
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: sudo unzip -o release.zip

      - name: Change ownership of the deployment directory
        run: sudo chown -R www-data:www-data /var/www/wcrops

      - name: Deploy to local server
        run: |
          # Navigate to the Laravel project directory
          cd /var/www/wcrops

          # Install Composer dependencies
          composer install --no-interaction --prefer-dist --optimize-autoloader

          # Run Laravel migrations
          php artisan migrate --force

          # Cache configurations
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
