name: Build and deploy PHP app to local server - w-crops

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install zip utility
        run: sudo apt-get install zip -y

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build --if-present

      - name: Check if composer.json exists
        id: check_files
        run: test -f composer.json && echo "::set-output name=files_exists::true" || echo "::set-output name=files_exists::false"

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          sudo chown -R $USER:$USER /var/www/wcrops
          composer validate --no-check-publish
          composer install --no-interaction --prefer-dist --optimize-autoloader

  deploy:
    runs-on: self-hosted
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Change ownership of the deployment directory
        run: sudo chown -R www-data:www-data /var/www/wcrops

      - name: Deploy to local server
        run: |
          # Navigate to the Laravel project directory
          cd /var/www/wcrops

          # Run Laravel migrations
          php artisan migrate --force

          # Cache configurations
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache